import { Code } from '@qwery/domain/common';

export const ERROR_CODES = {
  BAD_REQUEST: Code.BAD_REQUEST_ERROR.code,
  UNAUTHORIZED: Code.UNAUTHORIZED_ERROR.code,
  WRONG_CREDENTIALS: Code.WRONG_CREDENTIALS_ERROR.code,
  ACCESS_DENIED: Code.ACCESS_DENIED_ERROR.code,
  INTERNAL_ERROR: Code.INTERNAL_ERROR.code,
  BAD_GATEWAY: Code.BAD_GATEWAY_ERROR.code,
  SERVICE_UNAVAILABLE: Code.SERVICE_UNAVAILABLE_ERROR.code,
  ENTITY_NOT_FOUND: Code.ENTITY_NOT_FOUND_ERROR.code,
  ENTITY_VALIDATION_ERROR: Code.ENTITY_VALIDATION_ERROR.code,
  USE_CASE_PORT_VALIDATION_ERROR: Code.USE_CASE_PORT_VALIDATION_ERROR.code,
  VALUE_OBJECT_VALIDATION_ERROR: Code.VALUE_OBJECT_VALIDATION_ERROR.code,
  ENTITY_ALREADY_EXISTS: Code.ENTITY_ALREADY_EXISTS_ERROR.code,
  NOTEBOOK_NOT_FOUND: Code.NOTEBOOK_NOT_FOUND_ERROR.code,
  NOTEBOOK_ALREADY_EXISTS: Code.NOTEBOOK_ALREADY_EXISTS_ERROR.code,
  NOTEBOOK_UPDATE_ERROR: Code.NOTEBOOK_UPDATE_ERROR.code,
  NOTEBOOK_DELETE_ERROR: Code.NOTEBOOK_DELETE_ERROR.code,
  NOTEBOOK_GET_ERROR: Code.NOTEBOOK_GET_ERROR.code,
  NOTEBOOK_GET_ALL_ERROR: Code.NOTEBOOK_GET_ALL_ERROR.code,
  NOTEBOOK_CREATE_ERROR: Code.NOTEBOOK_CREATE_ERROR.code,
  USER_NOT_FOUND: Code.USER_NOT_FOUND_ERROR.code,
  USER_ALREADY_EXISTS: Code.USER_ALREADY_EXISTS_ERROR.code,
  USER_UPDATE_ERROR: Code.USER_UPDATE_ERROR.code,
  USER_DELETE_ERROR: Code.USER_DELETE_ERROR.code,
  USER_GET_ERROR: Code.USER_GET_ERROR.code,
  USER_GET_ALL_ERROR: Code.USER_GET_ALL_ERROR.code,
  USER_CREATE_ERROR: Code.USER_CREATE_ERROR.code,
  WORKSPACE_NOT_FOUND: Code.WORKSPACE_NOT_FOUND_ERROR.code,
  WORKSPACE_UPDATE_ERROR: Code.WORKSPACE_UPDATE_ERROR.code,
  WORKSPACE_GET_ERROR: Code.WORKSPACE_GET_ERROR.code,
  WORKSPACE_CREATE_ERROR: Code.WORKSPACE_CREATE_ERROR.code,
  ORGANIZATION_NOT_FOUND: Code.ORGANIZATION_NOT_FOUND_ERROR.code,
  ORGANIZATION_UPDATE_ERROR: Code.ORGANIZATION_UPDATE_ERROR.code,
  ORGANIZATION_DELETE_ERROR: Code.ORGANIZATION_DELETE_ERROR.code,
  ORGANIZATION_GET_ERROR: Code.ORGANIZATION_GET_ERROR.code,
  ORGANIZATION_GET_ALL_ERROR: Code.ORGANIZATION_GET_ALL_ERROR.code,
  ORGANIZATION_CREATE_ERROR: Code.ORGANIZATION_CREATE_ERROR.code,
  PROJECT_NOT_FOUND: Code.PROJECT_NOT_FOUND_ERROR.code,
  PROJECT_UPDATE_ERROR: Code.PROJECT_UPDATE_ERROR.code,
  PROJECT_DELETE_ERROR: Code.PROJECT_DELETE_ERROR.code,
  PROJECT_GET_ERROR: Code.PROJECT_GET_ERROR.code,
  PROJECT_GET_ALL_ERROR: Code.PROJECT_GET_ALL_ERROR.code,
  PROJECT_CREATE_ERROR: Code.PROJECT_CREATE_ERROR.code,
  DATASOURCE_NOT_FOUND: Code.DATASOURCE_NOT_FOUND_ERROR.code,
  DATASOURCE_ALREADY_EXISTS: Code.DATASOURCE_ALREADY_EXISTS_ERROR.code,
  DATASOURCE_UPDATE_ERROR: Code.DATASOURCE_UPDATE_ERROR.code,
  DATASOURCE_DELETE_ERROR: Code.DATASOURCE_DELETE_ERROR.code,
  DATASOURCE_GET_ERROR: Code.DATASOURCE_GET_ERROR.code,
  DATASOURCE_GET_ALL_ERROR: Code.DATASOURCE_GET_ALL_ERROR.code,
  DATASOURCE_CREATE_ERROR: Code.DATASOURCE_CREATE_ERROR.code,
  AGENT_SESSION_NOT_FOUND: Code.AGENT_SESSION_NOT_FOUND_ERROR.code,
  STATE_MACHINE_NOT_FOUND: Code.STATE_MACHINE_NOT_FOUND_ERROR.code,
  INVALID_STATE_TRANSITION: Code.INVALID_STATE_TRANSITION_ERROR.code,
  CONVERSATION_NOT_FOUND: Code.CONVERSATION_NOT_FOUND_ERROR.code,
  CONVERSATION_ALREADY_EXISTS: Code.CONVERSATION_ALREADY_EXISTS_ERROR.code,
  CONVERSATION_UPDATE_ERROR: Code.CONVERSATION_UPDATE_ERROR.code,
  CONVERSATION_DELETE_ERROR: Code.CONVERSATION_DELETE_ERROR.code,
  CONVERSATION_GET_ERROR: Code.CONVERSATION_GET_ERROR.code,
  CONVERSATION_CREATE_ERROR: Code.CONVERSATION_CREATE_ERROR.code,
  MESSAGE_NOT_FOUND: Code.MESSAGE_NOT_FOUND_ERROR.code,
  MESSAGE_ALREADY_EXISTS: Code.MESSAGE_ALREADY_EXISTS_ERROR.code,
  MESSAGE_UPDATE_ERROR: Code.MESSAGE_UPDATE_ERROR.code,
  MESSAGE_DELETE_ERROR: Code.MESSAGE_DELETE_ERROR.code,
  MESSAGE_GET_ERROR: Code.MESSAGE_GET_ERROR.code,
  MESSAGE_CREATE_ERROR: Code.MESSAGE_CREATE_ERROR.code,
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export function getErrorCategory(
  code: number,
): 'notFound' | 'permissionDenied' | 'network' | 'generic' {
  if (code >= 2000 && code < 3000) return 'notFound';
  if (code === 401 || code === 403) return 'permissionDenied';
  if (code >= 400 && code < 500) return 'generic';
  if (code === 502 || code === 503 || code === 504) return 'network';
  return 'generic';
}

export function getErrorCategoryFromStatus(
  status: number,
): 'notFound' | 'permissionDenied' | 'network' | 'generic' {
  if (status === 401 || status === 403) return 'permissionDenied';
  if (status === 404) return 'notFound';
  if (status === 502 || status === 503 || status === 504 || status === 0) {
    return 'network';
  }
  return 'generic';
}
